name: Deploy docs

on:
  schedule:
    - cron: "0 0 1 1 *"
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-gh-pages.yml
      - docs/**
      - docusaurus.config.js
      - package.json
      - package-lock.json
      - sidebars.js
      - src/css/**
      - src/pages/**
      - static/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v5

      - name: Prepare Node environment
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - name: Build website
        run: |
          wget https://raw.githubusercontent.com/pranabdas/espresso/refs/heads/main/scripts/build_docusaurus.sh
          npm install
          bash build_docusaurus.sh

      - name: Deploy on gh-pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"

      - name: Build for cloudflare-pages
        run: |
          sed -i 's|^const site_url\s*=.*|const site_url="https://pranab.pages.dev";|I' docusaurus.config.js
          bash build_docusaurus.sh

      - name: Deploy on cloudflare
        if: ${{ github.event_name != 'schedule' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.CLOUDFLARE_DEPLOY_KEY }}
          publish_dir: build
          external_repository: ${{ github.repository_owner }}/${{ secrets.CLOUDFLARE_REPO_NAME }}
          publish_branch: cf-pages
          destination_dir: ${{ github.event.repository.name }}
          enable_jekyll: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
